# Generated by Django 5.2.3 on 2026-02-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='website',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
